name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: "actions/checkout@v2"

      # caching
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-

      - uses: actions/cache@v2
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-

      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-

      - uses: "actions/setup-python@v1"
        with:
          python-version: "${{ matrix.python-version }}"

      # Setup virtualenv
      - name: "Setup virtualenv for ${{ matrix.python-version }} on Linux or MacOS"
        if: startsWith(runner.os, 'macOS') || startsWith(runner.os, 'Linux')
        run: |
          python --version
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: "Run tox targets for ${{ matrix.python-version }} on Linux or MacOS"
        if: startsWith(runner.os, 'macOS') || startsWith(runner.os, 'Linux')
        shell: bash -l {0}
        run: |
          source .venv/bin/activate
          python -m tox
          ls
          ls tests

      - name: "Install requirements and run tox targets for ${{ matrix.python-version }} on Windows"
        if: startsWith(runner.os, 'Windows')
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m tox
          ls
          ls tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./tests/junit-*.xml
          fail_ci_if_error: true